const INITIALIZING_APP_SUCCESS = 'INITIALIZING_APP_SUCCESS';
const SET_COMPETITIONS = 'SET_COMPETITIONS';
const SET_TEAMS = 'SET_TEAMS';

export { INITIALIZING_APP_SUCCESS, SET_COMPETITIONS, SET_TEAMS }

