const INITIALIZING_APP_SUCCESS = 'INITIALIZING_APP_SUCCESS';
const SET_COMPETITIONS = 'SET_COMPETITIONS';
const SET_TEAMS = 'SET_TEAMS';
const SET_TEAM_CALENDAR = 'SET_TEAM_CALENDAR';
const CLEAN_TEAM_CALENDAR = 'CLEAN_TEAM_CALENDAR';
const SET_COMPETITION_CALENDAR = 'SET_COMPETITION_CALENDAR';
const CLEAN_COMPETITION_CALENDAR = 'CLEAN_COMPETITION_CALENDAR';

export { INITIALIZING_APP_SUCCESS, SET_COMPETITIONS, SET_TEAMS, SET_TEAM_CALENDAR, CLEAN_TEAM_CALENDAR, SET_COMPETITION_CALENDAR, CLEAN_COMPETITION_CALENDAR }

